name: symfony CI/CD
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mailog:
        image: mailhog/mailhog
        ports:
          - 1025:1025
          - 8025:8025
    steps:
      - uses: actions/checkout@v2
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: Install dependencies
        run: composer install
      - name: Run tests
        env:
          MAILER_DSN: smtp://localhost:1025
        run: php bin/phpunit
  Docker-build-push:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKERPASSWORD }}
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERUSERNAME }}/my-symfony-app:latest .
      - name: Push to Docker Hub
        run: docker push ${{ secrets.DOCKERUSERNAME }}/my-symfony-app:latest

       

    